
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: currency_development
  password:

test:
  <<: *default
  database: currency_test

production:
  <<: *default
  database: currency_production
