
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: currency_development
  password:

test:
  <<: *default
  database: currency_test

production:
  <<: *default
  host: ec2-107-21-125-143.compute-1.amazonaws.com
  database: demssq9ghg287a
  user: ykqwlxtzvsqwlt
  password: jwM_jVmH-LcDvpiGi9g5KYP-03
